plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: Jeroen van Wilgenburg's Blog
description: Java technology related articles
author: Jeroen van Wilgenburg
theme: jekyll-theme-modernist
google_analytics: G-BPX6BN6W30